backend/server/core/urls.py
from django.urls import include, path
from core import views

urlpatterns = [
    path( '', views.index, name='index' ),
]

backend/server/server/urls.py
from django.contrib import admin
from django.urls import include, path

from apps.accounts.urls import accounts_urlpatterns
from apps.notes.urls import notes_urlpatterns

urlpatterns = [
    path('api/', include('core.urls')),
    path('admin/', admin.site.urls),
    path('wopr/', include('wopr.urls')),
]

urlpatterns += accounts_urlpatterns # add URLs for authentication
urlpatterns += notes_urlpatterns # notes URLs

backend/server/wopr/urls.py
from django.urls import path
from django.views.generic import TemplateView

from . import views

app_name = 'wopr'
urlpatterns = [

    # Paths for 404, blank, and the index/dashboard
    path('', views.selectSite, name='index'),
    path('selectSite/', views.selectSite, name='selectSite'),
    path('dashboard/', views.dashboardSelectSite, name='dashboard'),
    path('blank/', TemplateView.as_view(template_name='wopr/blank.html'), name='blank'),
    path('instructions/', TemplateView.as_view(template_name='wopr/instructions.html'), name='instructions'),
    path('ieso/', views.iesoView, name='iesoUpload'),

    # Paths for edits, siteconfig, eventsData, and energyData
    path('editsTable/', TemplateView.as_view(template_name='wopr/editsTable.html'), name='edits-table'),

    path('siteconfig/', TemplateView.as_view(template_name='wopr/siteconfig.html'), name='site-config'),
    path('eventsData/', TemplateView.as_view(template_name='wopr/eventsData.html'), name='events-data'),
    path('energyData/', TemplateView.as_view(template_name='wopr/energyData.html'), name='energy-data'),

    path('timezone/', views.set_timezone, name='time-zone'),
    path('commitPage/', views.commitPage , name='commit-page'),

    # Paths for reports
    path('reports/editsReport/', views.getEditsReport , name='edits-report'),
    path('reports/powerCurveReport/', views.powerCurveView, name='powerCurve-report'),
    path('reports/powerCurveComparisonReport', views.powerCurveCompareView, name='powerCurve-report-compare'),
    path('reports/recurringFaultReport/', views.recurringFaultsView, name='recurFault-report'),
    path('reports/top20FaultsReport/', views.top20FaultsView, name='top20Fault-report'),
    path('reports/editsQualityCheckReport/', views.QualityCheckView, name='editsQuality-report'),
    path('reports/siteStartTimeEndTimeForm', views.QualityCheckView, name='site-start-end-form'),
    

    # Paths used by ajax calls
    path('filterEvent/', views.filterEvent, name='filter-event'),
    path('filterEnergy/', views.filterEnergy, name='filter-energy'),
    path('filterConfig/', views.filterConfig, name='filter-config'),
    path('filterEdits/', views.filterEdits, name='filter-edits'),
    path('filterTurbines/', views.filterTurbines, name='filter-turbines'),

    path('tsites/', views.getTSites, name='ajaxT_sites'),
    path('dashboard/<int:site>/', views.dashboard, name='dashboard-site'),
    path('editsTable/<int:site>', views.getEdits, name='ajax_edits'),
    path('siteconfig/<int:site>', views.getSiteConfig, name='ajaxT_siteconfig'),
    path('events/<int:site>', views.getEvents, name='ajaxT_eventdata'),
    path('energy/<int:site>', views.getEnergy, name='ajaxT_energydata'),
    path('postDashboardChanges/', views.postDashboardChanges, name='store-changes'),

    path('tenMinuteData/', views.ajaxTenMinuteData, name='ajax_TenMinuteData'),
    path('changesArray/', views.getChangesArray, name='ajax_changes_array'),
    path('commitChanges/', views.commitDashboardChanges, name='commit-changes'),
    path('discardChanges/', views.discardDashboardChanges, name='discard-changes'),
    path('storeSessionData/', views.storeSessionData, name='store-session-data'),
]

backend/server/wopr/models/circuits.py
from django.db import models

class TCircuits(models.Model):
    circuitid = models.IntegerField(db_column='CircuitID', primary_key=True)  # Field name made lowercase.
    id = models.IntegerField(db_column='ID')  # Field name made lowercase.
    siteid = models.IntegerField(db_column='siteID', blank=True, null=True)  # Field name made lowercase.

    class Meta:
        db_table = 't_Circuits'
        unique_together = (('circuitid', 'id'),)

backend/server/wopr/models/edits.py
from django.db import models

class TEdits(models.Model):
    editid = models.AutoField(db_column='EditID', primary_key=True)  # Field name made lowercase.
    ts_edit = models.DateTimeField()
    siteid = models.IntegerField(db_column='siteID')  # Field name made lowercase.
    id = models.IntegerField()
    period_from = models.IntegerField()
    period_to = models.IntegerField()
    fieldid = models.IntegerField(db_column='fieldID')  # Field name made lowercase.
    ts_editstart = models.DateTimeField(db_column='ts_EditStart')  # Field name made lowercase.
    ts_editend = models.DateTimeField(db_column='ts_EditEnd')  # Field name made lowercase.
    username = models.CharField(max_length=200)
    comment = models.CharField(max_length=2000, blank=True, null=True)
    newval = models.IntegerField(db_column='newVal', blank=True, null=True)  # Field name made lowercase.
    newvalfloat = models.FloatField(db_column='newValFloat', blank=True, null=True)  # Field name made lowercase.
    note = models.CharField(max_length=2000, blank=True, null=True)
    groupid = models.IntegerField(db_column='groupID', blank=True, null=True)  # Field name made lowercase.
    newval2 = models.IntegerField(db_column='newVal2', blank=True, null=True)  # Field name made lowercase.

    class Meta:
        db_table = 't_Edits'

backend/server/wopr/models/kks.py
from django.db import models

class TKksnames(models.Model):
    kks_name = models.CharField(db_column='KKS_Name', primary_key=True, max_length=50)  # Field name made lowercase.
    description = models.CharField(db_column='Description', max_length=50, blank=True, null=True)  # Field name made lowercase.

    class Meta:
        db_table = 't_KKSNames'

backend/server/wopr/forms/dashboard.py
from django import forms
from wopr.widgets import XDSoftDateTimePickerInput
from wopr.utils import makeTurbineList


class FilterDashboardForm(forms.Form):
    # Default values
    CHOICES = ['Turbine' + str(i + 1) for i in range(1, 100)]
    start_time = forms.DateTimeField(label='From Time', input_formats=['%d/%m/%Y %H:%M'], widget=XDSoftDateTimePickerInput(attrs={'autocomplete':'off'}))
    end_time = forms.DateTimeField(label='Till Time', input_formats=['%d/%m/%Y %H:%M'], widget=XDSoftDateTimePickerInput(attrs={'autocomplete':'off'}))
    id_from = forms.ChoiceField(label='From Turbine', choices=CHOICES)
    id_till = forms.ChoiceField(label='Till Turbine', choices=CHOICES)

    # Constructor with parameters
    def __init__(self, *args,**kwargs):
        self.siteid = kwargs.pop('siteid')
        self.id_from = kwargs.pop('id_from')
        self.id_till = kwargs.pop('id_till')
        self.CHOICES = makeTurbineList(self.siteid, self.id_from, self.id_till)
        self.lastIndex = self.CHOICES[len(self.CHOICES) - 1]
        super(FilterDashboardForm, self).__init__(*args, **kwargs)
        self.fields['id_from'] = forms.ChoiceField(label='From Turbine', choices=self.CHOICES)
        self.fields['id_till'] = forms.ChoiceField(label='Till Turbine', choices=self.CHOICES, initial=self.lastIndex)

    def clean(self):
        cleaned_data = super().clean()
        start_time = cleaned_data.get("start_time")
        end_time = cleaned_data.get("end_time")
        if start_time and end_time:
            if end_time <= start_time:
                print(str(end_time)+"<="+str(start_time)+" returned "+str(end_time <= start_time))
                raise forms.ValidationError(" - ERROR - Please ensure the time range is valid.")

backend/server/wopr/views.py
from .models import TSites, TSiteconfig, TEventdata, TEnergydata, TEdits, TPowercurves

from django.http import JsonResponse, HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from django.core import serializers
from django.forms.models import model_to_dict
from django.views.decorators.csrf import csrf_protect
from wopr.utils import *
from datetime import timedelta, datetime
import dateutil.parser
from django.core.serializers.json import DjangoJSONEncoder
from django.core.exceptions import ObjectDoesNotExist
import json
from django.db.models import Sum, Count, Q
from django.core.serializers.json import DjangoJSONEncoder
import copy
import os
import time
import pytz
from django.views.generic import TemplateView
from django.db.models import Min, Max, Value
from django.db import connection
from django.utils import timezone
from django.conf import settings as djangoSettings

from django.contrib.sessions.models import Session
from openpyxl import *
from operator import itemgetter
import pprint
from dateutil.parser import parse
import getpass


# from .forms import siteID_startTime_endTime, CommentForm
from .forms import *
# Create your views here.
# 1. Create index and details method here
# 2. Interact with model here
# 3. Pull our posts in
# 4. Load templates and views from here


# ------- Functions used to display the html with a certain dictionary ------- #

# Sets the timezone of the user by storing the timezone name in django_timezone which system will determine offset with
def set_timezone(request):

    if request.method == 'POST':
        if(request.POST.get('timezone')):

            tzname = request.POST.get('timezone')

            request.session['django_timezone'] = tzname
            request.session['local'] = tzname

            timezone.activate(pytz.timezone(tzname))
            print('TimezoneMiddleware activated timezone to', tzname, 'after POST.')

        return JsonResponse({"message": 'The timezone was successfully set to: '}, safe=False)
        
    else:
        return JsonResponse({"message": 'The request has to be a POST to set the timezone.'}, safe=False)

# Main page to select a site
def selectSite(request):
    
    # Check if the user is visiting the page
    if request.method == 'GET':

        # Resets the selected site everytime you click on select a site
        for key in request.session.keys():
            if key != 'django_timezone' and key != '_csrftoken':
                request.session[key] = ''
            
        form = SiteSelectionForm()
        return render(request, 'wopr/selectSite.html', {'form': form, 'title': 'Select a Site'})
        
        
    # Check if the request is a post
    if request.method == 'POST':
        form = SiteSelectionForm(request.POST)
        if form.is_valid():

            siteid = form.cleaned_data['site_id']
            sites_queryset = TSites.objects.filter(siteid__icontains=siteid).order_by('siteid')

            form = SiteSelectionForm()

            return HttpResponseRedirect('/wopr/dashboard/' + str(siteid))
            
        return render(request, 'wopr/selectSite.html', {'form': form,  'title': 'Select a Site', 'message': 'Please make sure to enter a valid site id.'})

# Get the site with the siteID 'site'
def getTSites(request):

    # Check whether the data parameters are valid
    if not(isNum(request.GET['siteid'])) or not(request.GET['siteid']):
        return JsonResponse({'status':'0', 'message': 'Please enter a valid site ID.'})
        
    # Check if the request is ajax and a type: "GET"
    if(request.is_ajax and request.GET):
        # Get the data parameters
        data = request.GET
        # Search the database where siteid = data['siteid']
        try:
            sites = TSites.objects.get(siteid=data['siteid']) # use Model.objects.get() if there is one object in the database or None

            # Convert the object to a dictionary with a format:
            # (example)
            #   {
            #       'id': "1",
            #       'name': "Bob"
            #   }
            #
            dictionary = model_to_dict(sites)

            # Add status and message to the dictionary
            dictionary['status'] = "1"
            dictionary['message'] = "Success"

            # Use sessions to store the selected site id
            request.session['siteid'] = data['siteid']
            # Set the sessions expiry to 10 minutes
            #request.session.set_expiry(600)

            # Send back the JSON containing the data of sites to the AJAX call
            # with a Content-Type header set to application/json 
            
            # The safe boolean parameter defaults to True. If it’s set to False, any object can be passed for serialization (otherwise only dict instances are allowed). 
            # If safe is True and a non-dict object is passed as the first argument, a TypeError will be raised.
            return JsonResponse(dictionary, safe=False)

        # Catch exception if the site does not exist
        except TSites.DoesNotExist:
            
           return JsonResponse({'status':'0','message':'The site number does not exist in the database'})
        
    return JsonResponse({'status':'0', 'message': 'Request must be Ajax of type "GET"'})

# Get the events with the siteID 'site'
def getEvents(request, site):

    t_events = TEventdata.objects.filter(siteid=site, id=1).order_by('ts_start')

    # Serialize to JSON format
    dataFromTemplate = serializers.serialize("json", t_events, default = dateConverter)

    return render(request, 'wopr/eventsData.html', {'json': dataFromTemplate})
    
# Get the energy data with the siteID 'site'
def getEnergy(request, site):

    t_energy = TEnergydata.objects.filter(siteid=site, id=1).order_by('ts')

    # Serialize to JSON format
    dataFromTemplate = serializers.serialize("json", t_energy, default = dateConverter)

    return render(request, 'wopr/energyData.html', {'json': dataFromTemplate})

# Get the site configuration for the siteID 'site'
def getSiteConfig(request, site):

    t_siteconfig = TSiteconfig.objects.filter(siteid=site).order_by('id')    

    # Serialize to JSON format
    dataFromTemplate = serializers.serialize("json", t_siteconfig, default = dateConverter)

    # Send back the JSON containing the data of t_sites to the AJAX call
    # with a Content-Type header set to application/json 
    return render(request, 'wopr/siteconfig.html', {'json': dataFromTemplate})    

# Get the edits table data for the siteID 'site'
def getEdits(request, site):

    t_edits = TEdits.objects.filter(siteid=site)    

    # Serialize to JSON format
    dataFromTemplate = serializers.serialize("json", t_edits, default = dateConverter)

    # Send back the JSON containing the data of t_sites to the AJAX call
    # with a Content-Type header set to application/json 
    return render(request, 'wopr/editsTable.html', {'json': dataFromTemplate})

# Get the changes array saved in session
def getChangesArray(request):
    if(request.is_ajax and request.method == 'GET'):
        return JsonResponse({"changesArray": request.session['changesArray'], "status": 1}, safe=False)
    else:
        return JsonResponse({"message": 'Please make sure your ajax request is a valid GET.', "status": 1}, safe=False)

# Get the site selection form for the dashboard page
def dashboardSelectSite(request):

    # Check if the user is visiting the page
    if request.method == 'GET':

        # Resets the selected site everytime you click on select a site
        for key in request.session.keys():
            if key != 'django_timezone' and key != '_csrftoken':
                request.session[key] = ''
            
        siteSelectionForm = SiteSelectionForm()
        return render(request, 'wopr/dashboard.html', {'siteSelectionForm': siteSelectionForm, 'title': 'Edits Allocation'})
        
        
    # Check if the request is a post
    if request.method == 'POST':
        siteSelectionForm = SiteSelectionForm(request.POST)
        if siteSelectionForm.is_valid():

            siteid = siteSelectionForm.cleaned_data['site_id']
            sites_queryset = TSites.objects.filter(siteid__icontains=siteid).order_by('siteid')

            siteSelectionForm = SiteSelectionForm()

            return HttpResponseRedirect('/wopr/dashboard/' + str(siteid))
            
        return render(request, 'wopr/dashboard.html', {'siteSelectionForm': siteSelectionForm,  'title': 'Edits Allocation'})

# Get the edits allocation turbine data for the siteID 'site'
def dashboard(request, site):
    start = time.time()

    # Get the colors corresponding to state and system from utils.py
    stateColorScheme = getStateColors()
    systemColorScheme = getSystemColors()
    system_description_list = [system for system in TSystems.objects.all().values('systemid', 'system', 'description', 'defined_state', 'definedstateid')]
    for system_type in systemColorScheme:
        system_type['descriptions'] = []
        for description in system_description_list:
            if(system_type['system'] == description['system']):
                system_type['descriptions'].append(description)

    # if it is get (initial visit) then make a blank form and render it.
    if request.method == 'GET':

        request.session['siteid'] = site # store the siteid in session

        # User wants to select another time range
        if('reselect' in request.GET):

            # Resets the selected site everytime you click on select a site
            for key in request.session.keys():
                if key != 'django_timezone' and key != '_csrftoken' and key != 'siteid':
                    request.session[key] = ''

            form = TurbineSelectionForm(siteid=site)
            # When there are no turbines in the database for that site
            if(form.CHOICES[0][0] == -1 and form.CHOICES[0][1] == 'There are no turbines available for this site.'):

backend/server/wopr/templates/wopr/editsTable.html
{% extends 'wopr/layout.html' %} {% load static %} {% block content %}

<div id="content-wrapper">
  <div class="container-fluid">
    <!-- Breadcrumbs -->
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'wopr:index' %}">Dashboard</a></li>
      {% if request.session.siteid %}
      <li class="breadcrumb-item">Site {{request.session.siteid}}</li>
      {% endif %}
      <li class="breadcrumb-item active">Edits</li>
    </ol>

    <!-- Page Content -->
    <h1>Edits Table</h1>
    <hr />
  

    {% if request.session.siteid %}
      <div>
        Select a User Name to filter the search:
        <input id="username" name="search" type="text" class="query-search" placeholder="Enter a username...">
        <input onclick="filterByUserName()" type="button" class="btn btn-primary" value = "Filter"/>
      </div>
      <i>Example: knoske, dseely, llessard </i>

      <hr>

      {% if json %}

      <!-- List of hooks-->
      <div id="hooksList"></div>
      <!-- Edits Table -->
      <div id="editstable"></div>

      <hr>

      <!-- Displays the Console, the commit button, and the event callbacks-->
      <div class="panel panel-primary" id="events-table">
      
      <div class="panel-body" id="events">
      
      
      <script type='text/javascript' name='editsScript'>

        // Array that will keep track of each changes in the data
        var changesArray = new Array();

        // Variable that will represent the table
        var handsontable, objectArray;
        
        // Counter for the comments
        var counter = 1;

        var start = new Date().getTime(), timer;

        $(document).ready(function(){
            // Parse the JSON response
            var json = JSON.parse("{{json | escapejs}}");

            // Define the array of objects with the length of keys from the json response
            objectArray = new Array(Object.keys(json).length);
                
            // Add in the primary key value to the fields of the JSON since it does not read it as a field
            for(const i in json){
              var siteConfigObj = {
                editid: json[i].pk
              };
              // Merge the two objects
              siteConfigObj = {...siteConfigObj, ...json[i].fields};
              // Store the merged object to an array for the Handsontable to read
              objectArray[i] = siteConfigObj;
            }

            // Tutorial for writing a callback at https://handsontable.com/docs/6.2.0/tutorial-using-callbacks.html
            config = {
              data: objectArray,
              colHeaders:  ['EditID', 'ts_edit', 'siteID', 'id','period_from','period_to','fieldID','ts_EditStart',
              'ts_EditEnd', 'username','comment', 'newVal'],
              columns :
                      [{data: 'editid'},{data: 'ts_edit'},{data: 'siteid'} ,{data: 'id'} ,{data: 'period_from'}, {data: 'period_to'},
                         {data: 'fieldid'}, {data: 'ts_editstart'}, {data: 'ts_editend'}, {data: 'username'}
                         ,{data: 'comment'}, {data: 'newval'}
                      ],
              minSpareRows: 1,
              manualColumnResize: true,
              manualRowResize: true,
              height: 400
              
            }

            var i = 0;

            $hooksList = $('#hooksList');
            var hooks = Handsontable.hooks.getRegistered();
            
            
            var events = document.getElementById("events");

            handsontable = new Handsontable(document.getElementById('editstable'), config);

            
        });

        /* Function called to filter the data by the username */
        function filterByUserName(){
          var username_val = $("#username").val();
  
          $.ajax({
            url: "{% url 'wopr:filter-edits' %}",
            data:{
              "username": username_val,
              "siteid": "{{request.session.siteid}}"
  
            },
            type: "GET",
            success: function (dataFromTemplate) {
              
              //Comment out to see the response from the AJAX call
              //console.log(dataFromTemplate);
  
              // Parse the JSON response
              var json = JSON.parse(dataFromTemplate);
              // Define the array of objects with the length of keys from the json response
              objectArray = new Array(Object.keys(json).length);
  
              // Add in the primary key value to the fields of the JSON since it does not read it as a field
              for(const i in json){
                var siteConfigObj = {
                  editid: json[i].pk
                };
                // Merge the two objects
                siteConfigObj = {...siteConfigObj, ...json[i].fields};
                // Store the merged object to an array for the Handsontable to read
                objectArray[i] = siteConfigObj;
              }

              // Update the data of the table and the callback since the objectArray changed              
              handsontable.updateSettings({
                data: objectArray
              })
            },
            error: function(error_data){
                console.log("error")
                console.log(error_data)
            }
          });
        }

      </script>
      {% endif %}
    {% else %}
    <div>
      <p>Select a site to view its edits data :</p>
      <input id="siteid" name="search" type="text" class="query-search" placeholder="Enter a siteID...(1432)">
      <input onclick="getSites()" type="button" class="btn btn-primary" value = "Search"/>
      <hr />
      <h2 id="resultsheader"></h2>
      <ul class="list-group">
      <div id="siteResults"></div>
      </ul>
  </div>

    <script>
        function getSites(){

          $('#resultsheader').empty();
          $('#siteResults').empty();
  
          $.ajax({
            url: "{% url 'wopr:ajaxT_sites' %}",
            data: {"siteid": $("#siteid").val()},
            type: "GET",
            success: function (dataFromTemplate) {

                if(dataFromTemplate.status){
                   
                    var path =  '<a href=' + "\"" + "wopr/editsTable/" + dataFromTemplate.siteid.toString() + "\""  +">"
                    $('#resultsheader').append("Search Results");
                    $('#siteResults').append('<li class="list-group-item">' + path + "Site No. " + dataFromTemplate.siteid + '</li>');
                }
                else
                    alert(dataFromTemplate.message);
            },
            error: function(error_data){
                console.log("error")
                console.log(error_data)
            }
          });
        }
    </script>
    {% endif %}
  </div>
  <!-- /.container-fluid -->
</div>
<!-- /.content-wrapper -->
</div>
<!-- /#wrapper -->

{% endblock %}

backend/server/wopr/templates/wopr/ieso.html
{% extends 'wopr/layout.html' %} {%block content %}
<div id="content-wrapper">
    <div class="container-fluid">
        <!-- Breadcrumbs -->
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'wopr:index' %}">Dashboard</a></li>
            <li class="breadcrumb-item active">IESO File Upload</li>
        </ol>

        <!-- Page Content -->
        <h1>IESO file upload</h1>
        <hr />
        <form action="{% url 'wopr:iesoUpload' %}" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <br>
            {% if form.errors %}
            {{form.errors}}
            {% endif %}
            <br>
            Please select an IESO file for upload: {{ form.IESO_file }}
            <br><br>
            {{ form.useMidnight }}
            if no release is found for a mandatory dispatch, use midnight of the following day as the end date
            <br><br>
            <input class='btn-success' type="submit" value="Upload" name="file" id="file">
        </form>
        {% if dialog %}
        <br>
            <h4>Selected file: {{file}}</h4>
            <br><br>
            <b>No end found for mandatory dispatch at {{dispatch}}. <br>Use {{dialog}}?</b> 
            <br><br>
            <ul style="list-style-type: none; text-align: left">
                <li style="display: inline-block">
                    <form action="{% url 'wopr:iesoUpload' %}" method="POST">
                        {% csrf_token %}
                        <input type="hidden" name="answered" value="{{file}}">
                        <input class='btn-success' style="margin: 10px" type="submit" value="Yes">
                    </form>
                </li>
                <li style="display: inline-block">
                    <form action="{% url 'wopr:iesoUpload' %}" method="GET">
                        <input class='btn-success' style="margin: 10px" type="submit" value="No">
                    </form>
                </li>
            </ul>
        {% elif invalid %}
            <br>
            <h4>The selected file: <br>{{invalid}}<br>
            {{result}} </h4>
        {% elif valid %}
            <br>
            <h4>Selected file: {{valid}}</h4>
            <br><br>
            <ul>
                {% for item in result %}
                <li>dbo.sp_UpdateStateSystemWhereCTH {{item}}</li>
                {% endfor %}
            </ul>
            {% if errors %}
                <br><br>
                <b>The following errors occurred:</b>
                <ul>
                    {% for item in errors %}
                    <li>{{item}}</li>
                    {% endfor %}
                </ul>
            {% endif %}
            <br><br>
            <ul style="list-style-type: none; text-align: left">
                <li style="display: inline-block">
                    <form action="{% url 'wopr:iesoUpload' %}" method="POST">
                        {% csrf_token %}
                        <input type="hidden" name="accepted_scripts" id="accepted_scripts" value="{{result}}">
                        <input class='btn-success' style="margin: 10px" type="submit" value="Accept">
                    </form>
                </li>
                <li style="display: inline-block">
                    <form action="{% url 'wopr:iesoUpload' %}" method="GET">
                        <input class='btn-success' style="margin: 10px" type="submit" value="Reject">
                    </form>
                </li>
            </ul>
            
        {% endif %}
    </div>
    <!-- /.container-fluid -->
</div>
<!-- /.content-wrapper -->
{% endblock %}

backend/server/wopr/templates/wopr/selectSite.html
{% extends 'wopr/layout.html' %} {%block content %}

<div id="content-wrapper">
    <div class="container-fluid">
      <!-- Page Content -->
      <h1>{{title}}</h1>

      <hr>
      
      <div>
        <form action="{% url 'wopr:selectSite' %}" method="post">
            {% csrf_token %}
            {{ form }}
            <input class='btn-success' type="submit" value="Select">
        </form>
      </div>

      <script>
        if('{{message}}'){
          alert('{{message}}');
        }
        const databaseName = 'data_storage';
        var req = indexedDB.deleteDatabase(databaseName);
        req.onsuccess = function () {
        };
        req.onerror = function () {
            console.log("Couldn't delete database");
        };
        req.onblocked = function () {
            console.log("Couldn't delete database due to the operation being blocked");
        };
      </script>

    </div>
    <!-- /.container-fluid -->
  </div>
  <!-- /.content-wrapper -->
</div>
<!-- /#wrapper -->

{% endblock %}