backend/server/core/urls.py
from django.urls import include, path
from core import views

urlpatterns = [
    path( '', views.index, name='index' ),
]

backend/server/server/urls.py
from django.contrib import admin
from django.urls import include, path

from apps.accounts.urls import accounts_urlpatterns
from apps.notes.urls import notes_urlpatterns

urlpatterns = [
    path('api/', include('core.urls')),
    path('admin/', admin.site.urls),
    path('wopr/', include('wopr.urls')),
]

urlpatterns += accounts_urlpatterns # add URLs for authentication
urlpatterns += notes_urlpatterns # notes URLs

backend/server/wopr/urls.py
from django.urls import path
from django.views.generic import TemplateView

from . import views

app_name = 'wopr'
urlpatterns = [

    # Paths for 404, blank, and the index/dashboard
    path('', views.selectSite, name='index'),
    path('selectSite/', views.selectSite, name='selectSite'),
    path('dashboard/', views.dashboardSelectSite, name='dashboard'),
    path('blank/', TemplateView.as_view(template_name='wopr/blank.html'), name='blank'),
    path('instructions/', TemplateView.as_view(template_name='wopr/instructions.html'), name='instructions'),
    path('ieso/', views.iesoView, name='iesoUpload'),

    # Paths for edits, siteconfig, eventsData, and energyData
    path('editsTable/', TemplateView.as_view(template_name='wopr/editsTable.html'), name='edits-table'),

    path('siteconfig/', TemplateView.as_view(template_name='wopr/siteconfig.html'), name='site-config'),
    path('eventsData/', TemplateView.as_view(template_name='wopr/eventsData.html'), name='events-data'),
    path('energyData/', TemplateView.as_view(template_name='wopr/energyData.html'), name='energy-data'),

    path('timezone/', views.set_timezone, name='time-zone'),
    path('commitPage/', views.commitPage , name='commit-page'),

    # Paths for reports
    path('reports/editsReport/', views.getEditsReport , name='edits-report'),
    path('reports/powerCurveReport/', views.powerCurveView, name='powerCurve-report'),
    path('reports/powerCurveComparisonReport', views.powerCurveCompareView, name='powerCurve-report-compare'),
    path('reports/recurringFaultReport/', views.recurringFaultsView, name='recurFault-report'),
    path('reports/top20FaultsReport/', views.top20FaultsView, name='top20Fault-report'),
    path('reports/editsQualityCheckReport/', views.QualityCheckView, name='editsQuality-report'),
    path('reports/siteStartTimeEndTimeForm', views.QualityCheckView, name='site-start-end-form'),
    

    # Paths used by ajax calls
    path('filterEvent/', views.filterEvent, name='filter-event'),
    path('filterEnergy/', views.filterEnergy, name='filter-energy'),
    path('filterConfig/', views.filterConfig, name='filter-config'),
    path('filterEdits/', views.filterEdits, name='filter-edits'),
    path('filterTurbines/', views.filterTurbines, name='filter-turbines'),

    path('tsites/', views.getTSites, name='ajaxT_sites'),
    path('dashboard/<int:site>/', views.dashboard, name='dashboard-site'),
    path('editsTable/<int:site>', views.getEdits, name='ajax_edits'),
    path('siteconfig/<int:site>', views.getSiteConfig, name='ajaxT_siteconfig'),
    path('events/<int:site>', views.getEvents, name='ajaxT_eventdata'),
    path('energy/<int:site>', views.getEnergy, name='ajaxT_energydata'),
    path('postDashboardChanges/', views.postDashboardChanges, name='store-changes'),

    path('tenMinuteData/', views.ajaxTenMinuteData, name='ajax_TenMinuteData'),
    path('changesArray/', views.getChangesArray, name='ajax_changes_array'),
    path('commitChanges/', views.commitDashboardChanges, name='commit-changes'),
    path('discardChanges/', views.discardDashboardChanges, name='discard-changes'),
    path('storeSessionData/', views.storeSessionData, name='store-session-data'),
]

backend/server/wopr/models/circuits.py
from django.db import models

class TCircuits(models.Model):
    circuitid = models.IntegerField(db_column='CircuitID', primary_key=True)  # Field name made lowercase.
    id = models.IntegerField(db_column='ID')  # Field name made lowercase.
    siteid = models.IntegerField(db_column='siteID', blank=True, null=True)  # Field name made lowercase.

    class Meta:
        db_table = 't_Circuits'
        unique_together = (('circuitid', 'id'),)

backend/server/wopr/models/kks.py
from django.db import models

class TKksnames(models.Model):
    kks_name = models.CharField(db_column='KKS_Name', primary_key=True, max_length=50)  # Field name made lowercase.
    description = models.CharField(db_column='Description', max_length=50, blank=True, null=True)  # Field name made lowercase.

    class Meta:
        db_table = 't_KKSNames'

backend/server/wopr/forms/dashboard.py
from django import forms
from wopr.widgets import XDSoftDateTimePickerInput
from wopr.utils import makeTurbineList


class FilterDashboardForm(forms.Form):
    # Default values
    CHOICES = ['Turbine' + str(i + 1) for i in range(1, 100)]
    start_time = forms.DateTimeField(label='From Time', input_formats=['%d/%m/%Y %H:%M'], widget=XDSoftDateTimePickerInput(attrs={'autocomplete':'off'}))
    end_time = forms.DateTimeField(label='Till Time', input_formats=['%d/%m/%Y %H:%M'], widget=XDSoftDateTimePickerInput(attrs={'autocomplete':'off'}))
    id_from = forms.ChoiceField(label='From Turbine', choices=CHOICES)
    id_till = forms.ChoiceField(label='Till Turbine', choices=CHOICES)

    # Constructor with parameters
    def __init__(self, *args,**kwargs):
        self.siteid = kwargs.pop('siteid')
        self.id_from = kwargs.pop('id_from')
        self.id_till = kwargs.pop('id_till')
        self.CHOICES = makeTurbineList(self.siteid, self.id_from, self.id_till)
        self.lastIndex = self.CHOICES[len(self.CHOICES) - 1]
        super(FilterDashboardForm, self).__init__(*args, **kwargs)
        self.fields['id_from'] = forms.ChoiceField(label='From Turbine', choices=self.CHOICES)
        self.fields['id_till'] = forms.ChoiceField(label='Till Turbine', choices=self.CHOICES, initial=self.lastIndex)

    def clean(self):
        cleaned_data = super().clean()
        start_time = cleaned_data.get("start_time")
        end_time = cleaned_data.get("end_time")
        if start_time and end_time:
            if end_time <= start_time:
                print(str(end_time)+"<="+str(start_time)+" returned "+str(end_time <= start_time))
                raise forms.ValidationError(" - ERROR - Please ensure the time range is valid.")

backend/server/wopr/forms/edits.py
from django import forms
from wopr.widgets import XDSoftDateTimePickerInput
from django.core.validators import FileExtensionValidator


class UsernameForm(forms.Form):
    CHOICES = [('knoske','knoske'), ('dseely','dseely'), ('llessard','llessard')]
    usernames = forms.CharField(label='User ', widget=forms.Select(choices=CHOICES))
    site_selected = forms.CharField(widget=forms.HiddenInput())

class EditsTableForm(forms.Form):
    start_time = forms.DateTimeField(input_formats=['%d/%m/%Y %H:%M'], widget=XDSoftDateTimePickerInput(attrs={'autocomplete':'off'}))
    end_time = forms.DateTimeField(input_formats=['%d/%m/%Y %H:%M'], widget=XDSoftDateTimePickerInput(attrs={'autocomplete':'off'}))
    CHOICES = [('knoske','knoske'), ('dseely','dseely'), ('llessard','llessard')]
    usernames = forms.CharField(label='User ', widget=forms.Select(choices=CHOICES))
    site_selected = forms.CharField(widget=forms.HiddenInput())
    def clean(self):
        cleaned_data = super().clean()
        start_time = cleaned_data.get("start_time")
        end_time = cleaned_data.get("end_time")
        if start_time and end_time:
            if end_time <= start_time:
                print(str(end_time)+"<="+str(start_time)+" returned "+str(end_time <= start_time))
                raise forms.ValidationError(" - ERROR - Please ensure the time range is valid.")


class UploadIESOFileForm(forms.Form):
    IESO_file = forms.FileField(validators=[FileExtensionValidator(allowed_extensions=['xlsx'])])
    useMidnight = forms.BooleanField(initial=True, required=False)


# class DateForm(forms.Form):
#     date = forms.DateTimeField(
#         input_formats=['%d/%m/%Y %H:%M'], 
#         widget=XDSoftDateTimePickerInput()
#     )

# class CommentForm(forms.Form):
#     name = forms.CharField()
#     url = forms.URLField()
#     comment = forms.CharField(widget=forms.Textarea)

# class oldSiteDateTimeForm(forms.Form):
#     site_id = forms.CharField()
#     start_time = forms.CharField(widget=forms.DateTimeInput())
#     end_time = forms.DateTimeField(widget=forms.DateTimeInput())

# class bsSiteDateTimeForm(forms.Form):
#     site_id = forms.CharField() # this needs to be a list from the database... kinda like below birth year picker
#     start_time = forms.DateTimeField(input_formats=['%d/%m/%Y %h:%M %A'], widget=BootstrapDateTimePickerInput())
#     end_time = forms.DateTimeField(input_formats=['%d/%m/%Y %h:%M %A'], widget=BootstrapDateTimePickerInput()) #2012-03-10 14:30

# class siteID_startTime_endTime(forms.Form):
#     siteID = forms.NumberInput()
#     startTime = forms.DateTimeInput()
#     endTime = forms.DateTimeInput()

# BIRTH_YEAR_CHOICES = ('1980', '1981', '1982')
# FAVORITE_COLORS_CHOICES = (
#     ('blue', 'Blue'),
#     ('green', 'Green'),
#     ('black', 'Black'),
# )



# class SimpleForm(forms.Form):
#     birth_year = forms.DateField(widget=forms.SelectDateWidget(years=BIRTH_YEAR_CHOICES))
#     favorite_colors = forms.MultipleChoiceField(
#         required=False,
#         widget=forms.CheckboxSelectMultiple,
#         choices=FAVORITE_COLORS_CHOICES,
#     )

backend/server/wopr/forms/site.py
from django import forms
from wopr.utils import makeChoicesList_EditsQualityCheck, makeSiteList
from wopr.widgets import XDSoftDateTimePickerInput
from wopr.models import TSites, TSiteconfig


class SiteDateTimeForm(forms.Form):
    site_id = forms.CharField(widget=forms.Select(choices=[])) # this needs to be a list from the database... kinda like below birth year picker
    start_time = forms.DateTimeField(input_formats=['%d/%m/%Y %H:%M'], widget=XDSoftDateTimePickerInput(attrs={'autocomplete':'off'}))
    end_time = forms.DateTimeField(input_formats=['%d/%m/%Y %H:%M'], widget=XDSoftDateTimePickerInput(attrs={'autocomplete':'off'})) #2012-03-10 14:30


    def __init__( self, *args, **kargs ):
        super().__init__( *args, **kargs )
        self.fields[ 'site_id' ].choices = makeChoicesList_EditsQualityCheck()

class SiteTimeRangeForm(forms.Form):
    #site_id = forms.CharField(widget=forms.Select(choices=CHOICES)) 
    site_id = forms.ModelChoiceField(queryset=TSites.objects.all()) 
    start_time = forms.DateTimeField(input_formats=['%d/%m/%Y %H:%M'], widget=XDSoftDateTimePickerInput(attrs={'autocomplete':'off'}))
    end_time = forms.DateTimeField(input_formats=['%d/%m/%Y %H:%M'], widget=XDSoftDateTimePickerInput(attrs={'autocomplete':'off'}))
    def clean(self):
        cleaned_data = super().clean()
        start_time = cleaned_data.get("start_time")
        end_time = cleaned_data.get("end_time")
        if start_time and end_time:
            if end_time <= start_time:
                print(str(end_time)+"<="+str(start_time)+" returned "+str(end_time <= start_time))
                raise forms.ValidationError(" - ERROR - Please ensure the time range is valid.")
                #self.add_error('start_time', "Please ensure the time range is valid.")
                #self.add_error('end_time', "Please ensure the time range is valid.")


class TimeRangeForm(forms.Form):
    start_time = forms.DateTimeField(input_formats=['%d/%m/%Y %H:%M'], widget=XDSoftDateTimePickerInput(attrs={'autocomplete':'off'}))
    end_time = forms.DateTimeField(input_formats=['%d/%m/%Y %H:%M'], widget=XDSoftDateTimePickerInput(attrs={'autocomplete':'off'}))
    def clean(self):
        cleaned_data = super().clean()
        start_time = cleaned_data.get("start_time")
        end_time = cleaned_data.get("end_time")
        if start_time and end_time:
            if end_time <= start_time:
                print(str(end_time)+"<="+str(start_time)+" returned "+str(end_time <= start_time))
                raise forms.ValidationError(" - ERROR - Please ensure the time range is valid.")


class SiteSelectionForm(forms.Form):

    def __init__(self, *args, **kargs):
        super().__init__( *args, **kargs )
        self.fields[ 'site_id' ] = forms.ChoiceField( label = 'Site', choices = makeSiteList() )

class SiteTurbineTimeForm(forms.Form):
    site_id = forms.CharField(widget=forms.Select(choices=[]))
    turbine_id = forms.CharField(widget=forms.Select(choices={}))
    start_time = forms.DateTimeField(input_formats=['%d/%m/%Y %H:%M'], widget=XDSoftDateTimePickerInput(attrs={'autocomplete':'off'}))
    end_time = forms.DateTimeField(input_formats=['%d/%m/%Y %H:%M'], widget=XDSoftDateTimePickerInput(attrs={'autocomplete':'off'}))
    def clean(self):
        cleaned_data = super().clean()
        start_time = cleaned_data.get("start_time")
        end_time = cleaned_data.get("end_time")
        if start_time and end_time:
            if end_time <= start_time:
                print(str(end_time)+"<="+str(start_time)+" returned "+str(end_time <= start_time))
                raise forms.ValidationError(" - ERROR - Please ensure the time range is valid.")
                #self.add_error('start_time', "Please ensure the time range is valid.")
                #self.add_error('end_time', "Please ensure the time range is valid.")
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['turbine_id'].queryset = TSiteconfig.objects.none().values("turbine")
        self.fields[ 'site_id' ].choices = makeSiteList()

        if 'site_id' in self.data:
            try:
                site = int(self.data.get('site_id')) #need site id too...
                self.fields['turbine_id'].queryset = TSiteconfig.objects.filter(siteid=site).values('turbine')
            except (ValueError, TypeError):
                pass  # invalid input from the client; ignore and fallback to empty turbine queryset

backend/server/wopr/forms/turbine.py
from django import forms
from wopr.utils import makeTurbineList, makeSiteList
from wopr.models import TSiteconfig
from wopr.widgets import XDSoftDateTimePickerInput


class TurbineSelectionForm(forms.Form):
    # Default values
    CHOICES = list(range(1, 100))
    start_time = forms.DateTimeField(input_formats=['%d/%m/%Y %H:%M'], widget=XDSoftDateTimePickerInput(attrs={'autocomplete':'off'}))
    end_time = forms.DateTimeField(input_formats=['%d/%m/%Y %H:%M'], widget=XDSoftDateTimePickerInput(attrs={'autocomplete':'off'}))
    view_turbines_from = forms.ChoiceField(choices=CHOICES)
    view_turbines_till = forms.ChoiceField(choices=CHOICES)

    # Constructor with parameters
    def __init__(self, *args,**kwargs):
        self.siteid = kwargs.pop('siteid')
        self.CHOICES = makeTurbineList(self.siteid)
        super(TurbineSelectionForm, self).__init__(*args, **kwargs)
        self.fields['view_turbines_from'] = forms.ChoiceField(choices=self.CHOICES)
        self.fields['view_turbines_till'] = forms.ChoiceField(choices=self.CHOICES, initial=str(len(self.CHOICES)))


class CompareTurbinePowerForm(forms.Form):
    site_id_1 = forms.CharField(widget=forms.Select(choices=[]))
    turbine_id_1 = forms.CharField(widget=forms.Select(choices={}))
    start_time_1 = forms.DateTimeField(input_formats=['%d/%m/%Y %H:%M'], widget=XDSoftDateTimePickerInput(attrs={'autocomplete':'off'}))
    end_time_1 = forms.DateTimeField(input_formats=['%d/%m/%Y %H:%M'], widget=XDSoftDateTimePickerInput(attrs={'autocomplete':'off'}))

    site_id_2 = forms.CharField(widget=forms.Select(choices=[]))
    turbine_id_2 = forms.CharField(widget=forms.Select(choices={}))
    start_time_2 = forms.DateTimeField(input_formats=['%d/%m/%Y %H:%M'], widget=XDSoftDateTimePickerInput(attrs={'autocomplete':'off'}))
    end_time_2 = forms.DateTimeField(input_formats=['%d/%m/%Y %H:%M'], widget=XDSoftDateTimePickerInput(attrs={'autocomplete':'off'}))
    def clean(self):
        cleaned_data = super().clean()
        start_time_1 = cleaned_data.get("start_time_1")
        end_time_1 = cleaned_data.get("end_time_1")
        start_time_2 = cleaned_data.get("start_time_2")
        end_time_2 = cleaned_data.get("end_time_2")
        if start_time_1 and end_time_1 and start_time_2 and end_time_2:
            if (end_time_1 <= start_time_1) or (end_time_2 <= start_time_2):
                print(str(end_time)+"<="+str(start_time)+" returned "+str(end_time <= start_time))
                raise forms.ValidationError(" - ERROR - Please ensure the time ranges are valid.")

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['turbine_id_1'].queryset = TSiteconfig.objects.none().values("turbine")

        self.fields[ 'site_id_1' ].choices = makeSiteList()
        self.fields[ 'site_id_2' ].choices = makeSiteList()


        if 'site_id_1' in self.data:
            try:
                site = int(self.data.get('site_id_1')) #need site id too...
                self.fields['turbine_id_1'].queryset = TSiteconfig.objects.filter(siteid=site).values('turbine')
            except (ValueError, TypeError):
                pass  # invalid input from the client; ignore and fallback to empty turbine queryset
        if 'site_id_2' in self.data:
            try:
                site = int(self.data.get('site_id_2')) #need site id too...
                self.fields['turbine_id_2'].queryset = TSiteconfig.objects.filter(siteid=site).values('turbine')
            except (ValueError, TypeError):
                pass  # invalid input from the client; ignore and fallback to empty turbine queryset

backend/server/wopr/templates/wopr/reports/editsQualityCheckReport.html
{% extends 'wopr/layout.html' %} {% block content %}

<div id="content-wrapper">
    <div class="container-fluid">
      <!-- Breadcrumbs -->
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'wopr:index' %}">Dashboard</a></li>
        <li class="breadcrumb-item active">Reports Form</li>
      </ol>

      <!-- Page Content -->
      <h2>Edits Quality Checks Report</h2>
      <br><small>The datetimes to input here are the time that the edit was made UTC. Format: DD/MM/YYYY. The HH:MM for a day dont matter for this report.</small>
      <br><small>Example: Sooderglen &emsp; 05/08/2015 00:00  &emsp;  05/08/2015 00:00</small>
      <br><small>Example: Sooderglen &emsp; 15/11/2017 00:00  &emsp;  17/11/2017 00:00</small>
      <br><small>Example: Sooderglen &emsp; 08/03/2012 00:00  &emsp;  15/03/2012 00:00</small>
      <div>
            <form action="{% url 'wopr:editsQuality-report' %}" method="post">
                {% csrf_token %}
                {{ form }}
                <input class='btn-success' type="submit" value="Submit">
            </form>
      </div>

      <DIV>
          {% if occurrences_report %}
          <h1>Occurrences Table</h1>
            <table class="table">
                <tr>
                <th>Date</th>
                <th>Edited CTH w/ non-CTH system</th>
                <th>No Data</th>
                <th>State Change Mid-Event</th>
                <th>System Change Mid-Event</th>
                <th>Blue & Red Boxes not marked</th>
                <th>Site Boxes not marked</th>
                </tr>
            {% for item in occurrences_report %}
                <tr> 
                <td class="small">{{ item.0 }}</td>
                <td class="small">{{ item.1 }}</td>
                <td class="small">{{ item.2 }}</td>
                <td class="small">{{ item.3 }}</td>
                <td class="small">{{ item.4 }}</td>
                <td class="small">{{ item.5 }}</td>
                <td class="small">{{ item.6 }}</td>
                </tr>
            {% endfor %}
            </table>
            {% endif %}
      </DIV>


    </div>
    <!-- /.container-fluid -->
  </div>
  <!-- /.content-wrapper -->
</div>
<!-- /#wrapper -->

{% endblock %}

backend/server/wopr/templates/wopr/reports/powerCurveReport.html
{% extends 'wopr/layout.html' %} {% load static %} {%block content %}
<!DOCTYPE html>
<html>
    <head> 
        <meta charset='utf-8' />
        <title> Power Curve Report </title> 
        <link rel="stylesheet" href="{% static 'wopr/css/powerCurveGraphStyle.css' %}">
        <script src="https://d3js.org/d3.v3.min.js" charset="utf-8"></script>
        <style>
        </style>
    </head> 
    <body>
        <div id="content-wrapper">
            <div class="container-fluid">
                <!-- Breadcrumbs -->
                <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="wopr/index.html">Dashboard</a></li>
                <li class="breadcrumb-item active">Power Curve Report</li>
                </ol>
                <!-- Page Content -->
                <h1>Power Curve Report</h1>
                <hr />
                <!-- Form -->
                <form action="{% url 'wopr:powerCurve-report' %}" id="siteTurbineTimeForm" load-turbines-url="{% url 'wopr:filter-turbines' %}" method="post">
                    {% csrf_token %}
                    {{ form }}
                    <input class='btn-success' type="submit" value="View Power Curve">
                </form>
                <p>Suggested: 09/03/2012 12:00:00 to 15/03/2012 05:30:00</p> 
                {% if form2 %}
                    <h2>Or Compare Turbines:<br /></h2>
                    <form action="{% url 'wopr:powerCurve-report-compare' %}" id="compareWithForm" load-turbines-url="{% url 'wopr:filter-turbines' %}" method="post">
                        {% csrf_token %}
                        {{ form2 }}
                        <input class='btn-success' type="submit" value="Compare">
                    </form>
                {% endif %}
                <script>
                    

                    $("#id_site_id").change(function () {
                      var url = $("#siteTurbineTimeForm").attr("load-turbines-url");  // get the url of the view
                      var siteId = $(this).val();  // get the selected site ID from the HTML input
                
                      $.ajax({                       // initialize an AJAX request
                        url: url,                    // set the url of the request 
                        data: {
                          'site_id': siteId       // add the site id to the GET parameters
                        },
                        success: function (data) {   // `data` is the return of the view function
                          $("#id_turbine_id").html(data);  // replace the contents of the turbine input with the data that came from the server
                        }
                      });
                    });

                      $("#id_site_id_1").change(function () {
                      var url = $("#compareWithForm").attr("load-turbines-url");  // get the url of the view
                      var siteId = $(this).val();  // get the selected site ID from the HTML input
                
                      $.ajax({                       // initialize an AJAX request
                        url: url,                    // set the url of the request 
                        data: {
                          'site_id': siteId       // add the site id to the GET parameters
                        },
                        success: function (data) {   // `data` is the return of the view function
                          $("#id_turbine_id_1").html(data);  // replace the contents of the turbine input with the data that came from the server
                        }
                      });
                    });

                      $("#id_site_id_2").change(function () {
                      var url = $("#compareWithForm").attr("load-turbines-url");  // get the url of the view
                      var siteId = $(this).val();  // get the selected site ID from the HTML input
                
                      $.ajax({                       // initialize an AJAX request
                        url: url,                    // set the url of the request
                        data: {
                          'site_id': siteId       // add the site id to the GET parameters
                        },
                        success: function (data) {   // `data` is the return of the view function
                          $("#id_turbine_id_2").html(data);  // replace the contents of the turbine input with the data that came from the server
                        }
                      });
                    });

                    //make an ajax call for the selected turbine
                      //when the page has been loaded, we should load the turbines based on default selection (or the one we picked if we've already submitted a form)
                      $(document).ready(function (){
                      if($("#id_site_id").val() == ' ')
                      {
                        return;
                      }
                      var url = $("#siteTurbineTimeForm").attr("load-turbines-url");  // get the url of the view
                      var siteId = $("#id_site_id").val();
              
                      $.ajax({                       // initialize an AJAX request
                        url: url,                    // set the url of the request 
                        data: {
                          'site_id': siteId       // add the site id to the GET parameters
                        },
                        success: function (data) {   // `data` is the return of the view function
                          $("#id_turbine_id").html(data);  // replace the contents of the turbine input with the data that came from the server
                          var field = document.getElementById('id_turbine_id');
                          field.selectedIndex = "{{selection.turbine_id|escapejs}}"; //finally, we select the one they had chosen when they submitted
                        }
                      });
              

                      });
                
                    
                  </script>
                        
                <!-- Result -->
                <!-- If the json file from the views is not null, it means the call is successful-->
                {% if selection %}
                    {% if powerJson and referenceCurveJson %}
                        <div id="powerCurve"></div>
                        <script>
                            console.log("{{selection | escapejs }}");
                            // parse json data into javascript arrays
                            var powerJSarray = JSON.parse("{{powerJson | escapejs}}");
                            var referenceJSarray = JSON.parse("{{referenceCurveJson | escapejs}}");

                            
                        </script>
                        <script src="{% static 'wopr/js/powerCurveGraph.js' %}"></script>
                        
                        
                        
                        
                    {% else %}
                        <br><br>
                        <p style='font-weight: bold; text-align: center'>No data available for this time range.</p>
                    {% endif %}
                {% endif %}
                

            </div>
            <!-- /.container-fluid -->
        </div>
        <!-- /.content-wrapper -->
    </body>
</html>

{% endblock %}

backend/server/wopr/templates/wopr/reports/siteStartTimeEndTimeForm.html
{% extends 'wopr/layout.html' %} {% block content %}

<div id="content-wrapper">
    <div class="container-fluid">
      <!-- Breadcrumbs -->
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'wopr:index' %}">Dashboard</a></li>
        <li class="breadcrumb-item active">Reports Form</li>
      </ol>

      <!-- THIS PAGE IS THE STARTING POINT FOR USING THE DATETIME PICKER FORM -->
      <div>
            <form action="{% url 'wopr:site-start-end-form' %}" method="post">
                {% csrf_token %}
                {{ form }}
                <input class='btn-success' type="submit" value="Submit">
            </form>
      </div>


    </div>
    <!-- /.container-fluid -->
  </div>
  <!-- /.content-wrapper -->
</div>
<!-- /#wrapper -->

{% endblock %}